"""Host injection points; no canonical application state is owned here."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, AsyncIterator, Mapping, Protocol

from .models import (
    CloseOperation, ControlOperation, NativeApprovalOperation, DiscoveryRequest, EventCursor,
    ExecutionContext, Inventory, LaunchIntent, OpenOperation, OperationReceipt,
    R4LeaseApplication,
    OperationKey, OwnedSlotPage, OwnedSlotState, PreparedLaunch, ReconcileReport, ReconcileRequest, RuntimeEvent,
    SessionKey, SessionClaimPage, SessionLeaseState, ProcessBirthEvidence,
    ProcessBirthRecord,
    ProcessBirthObservation,
    RuntimeSnapshot, ShutdownPolicy, ShutdownReport, StorageStatus,
    TurnOperation,
)
from .lease_reducer_r4 import R4LeaseAttempt


class RuntimeCore(Protocol):
    @property
    def r4_boot_id(self) -> str: ...
    async def begin_r4_lease_request(self, *, scope: Mapping[str, Any], grant_id: str,
                                      connection_id: str, connection_generation: int,
                                      purpose: str) -> R4LeaseAttempt: ...
    async def install_r4_lease(self, attempt: R4LeaseAttempt,
                               grant: Mapping[str, Any]) -> R4LeaseApplication: ...
    def r4_operation_context(self, frame: Mapping[str, Any], *,
                              connection_id: str,
                              connection_generation: int) -> ExecutionContext: ...
    def r4_native_action_context(self, scope: Mapping[str, Any], *,
                                 connection_id: str,
                                 connection_generation: int) -> ExecutionContext: ...
    async def revoke_r4_lease(self, context: ExecutionContext, *,
                              authorization_revision: int) -> R4LeaseApplication: ...
    async def discover(self, request: DiscoveryRequest) -> Inventory: ...
    async def prepare(self, intent: LaunchIntent,
                      context: ExecutionContext) -> PreparedLaunch: ...
    async def open(self, operation: OpenOperation,
                   context: ExecutionContext) -> OperationReceipt: ...
    async def submit(self, operation: TurnOperation,
                     context: ExecutionContext) -> OperationReceipt: ...
    async def control(self, operation: ControlOperation,
                      context: ExecutionContext) -> OperationReceipt: ...
    async def decide_native_approval(
            self, operation: NativeApprovalOperation,
            context: ExecutionContext) -> OperationReceipt: ...
    def events(self, cursor: EventCursor) -> AsyncIterator[RuntimeEvent]: ...
    async def acknowledge_events(self, cursor: EventCursor,
                                 through_sequence: int) -> int: ...
    async def compact_events(self, *, max_rows: int = 128) -> tuple[int, int]: ...
    async def storage_status(self) -> StorageStatus: ...
    async def checkpoint_wal(self) -> tuple[int, int, int]: ...
    async def inspect(self, session: SessionKey) -> RuntimeSnapshot: ...
    async def claimed_sessions(self, server_id: str, executor_id: str, *,
                               after_rowid: int = 0,
                               high_water_rowid: int | None = None,
                               limit: int = 128) -> SessionClaimPage: ...
    async def process_birth(self, session: SessionKey) -> ProcessBirthRecord | None: ...
    async def observe_process_birth(self, session: SessionKey) -> ProcessBirthObservation: ...
    async def reconcile(self, request: ReconcileRequest) -> ReconcileReport: ...
    async def close(self, operation: CloseOperation,
                    context: ExecutionContext, *,
                    wait_for_completion: bool = False) -> OperationReceipt: ...
    async def shutdown(self, policy: ShutdownPolicy) -> ShutdownReport: ...
    def shutdown_resources(self) -> Mapping[SessionKey, Mapping[str, object]]: ...
    async def renew_lease(self, session: SessionKey, context: ExecutionContext,
                          *, expected_connection_generation: int) -> RuntimeSnapshot: ...
    async def revoke_lease(self, session: SessionKey, context: ExecutionContext,
                           *, expected_connection_generation: int) -> None: ...


class Clock(Protocol):
    def monotonic(self) -> float: ...
    def wall_time(self) -> float: ...


class OwnedSlotLedger(Protocol):
    async def owned_slot_state(self, session: SessionKey) -> OwnedSlotState | None: ...
    async def reserve_owned_slot(self, key: OperationKey,
                                 session_id: str) -> None: ...
    async def release_owned_slot(self, key: OperationKey,
                                 session_id: str) -> bool: ...
    async def owned_slot_page(self, *, after_rowid: int = 0,
                              high_water_rowid: int | None = None,
                              limit: int = 128) -> OwnedSlotPage: ...


class Journal(OwnedSlotLedger, Protocol):
    async def admit(self, key: OperationKey, intent_hash: str, session_id: str,
                    *, critical: bool = False,
                    effect_imminent: bool = False,
                    claim_session: bool = False,
                    connection_generation: int | None = None,
                    session_owner_generation: int | None = None,
                    authorization_revision: int | None = None,
                    configuration_revision: int | None = None,
                    ) -> tuple[OperationReceipt, bool]: ...
    async def cas_session_lease(self, session: SessionKey, *,
                                expected_connection_generation: int,
                                connection_generation: int,
                                owner_generation: int,
                                authorization_revision: int,
                                configuration_revision: int,
                                revoked: bool) -> SessionLeaseState: ...
    async def get_session_lease(self, session: SessionKey) -> SessionLeaseState | None: ...
    async def mark_possible_effect(self, key: OperationKey) -> OperationReceipt: ...
    async def record_not_sent(self, key: OperationKey, error_code: str) -> OperationReceipt: ...
    async def record_receipt(self, key: OperationKey, receipt: OperationReceipt) -> OperationReceipt: ...
    async def get_receipt(self, key: OperationKey) -> OperationReceipt | None: ...
    async def claimed_sessions(self, server_id: str, executor_id: str, *,
                               after_rowid: int = 0,
                               high_water_rowid: int | None = None,
                               limit: int = 128) -> SessionClaimPage: ...
    async def record_process_birth(self, key: OperationKey, session_id: str,
                                   evidence: ProcessBirthEvidence) -> ProcessBirthRecord: ...
    async def get_process_birth(self, session: SessionKey) -> ProcessBirthRecord | None: ...
    async def append_event(self, event: RuntimeEvent) -> None: ...
    async def record_event(self, event: RuntimeEvent) -> RuntimeEvent: ...
    def events(self, cursor: EventCursor) -> AsyncIterator[RuntimeEvent]: ...
    async def contiguous_watermark(self, cursor: EventCursor) -> int: ...
    async def acknowledge_events(self, cursor: EventCursor,
                                 through_sequence: int) -> int: ...
    async def compact_acked(self, *, max_rows: int = 128) -> tuple[int, int]: ...
    async def storage_status(self) -> StorageStatus: ...
    async def checkpoint_wal(self) -> tuple[int, int, int]: ...


class ProcessBackend(Protocol):
    async def spawn(self, argv: tuple[str, ...], cwd: str,
                    env: Mapping[str, str]) -> Any: ...
    async def terminate_owned(self, handle: Any, deadline: float) -> str: ...


class SecretResolver(Protocol):
    async def resolve(self, reference: str) -> str: ...


class EventSink(Protocol):
    async def publish(self, event: RuntimeEvent) -> None: ...


if TYPE_CHECKING:
    from .native_action_bridge import NativeActionRequest


class NativeActionBridge(Protocol):
    async def invoke(self, request: NativeActionRequest,
                     context: ExecutionContext) -> Mapping[str, Any]: ...
